name: Build freqmon with custom rtl-sdr (Windows only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Установка MSYS2 для Windows (включает MinGW)
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gcc-libs
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libusb
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_ttf
          git
          mingw-w64-x86_64-make
          autoconf
          automake
          libtool
        update: true

    # Кэширование kissfft
    - name: Cache kissfft
      id: cache-kissfft
      uses: actions/cache@v4
      with:
        path: |
          /mingw64/lib/libkissfft-float.a
          /mingw64/include/kiss_fft.h
          /mingw64/include/kiss_fftr.h
        key: ${{ runner.os }}-kissfft-20241219

    # Установка kissfft вручную (исправленная версия)
    - name: Install kissfft manually
      if: steps.cache-kissfft.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        echo "Installing kissfft manually..."
        git clone https://github.com/mborgerding/kissfft.git  
        cd kissfft
        # Создаем директорию для объектных файлов
        mkdir -p obj
        # Компилируем основные файлы
        gcc -O3 -fPIC -I. -c kiss_fft.c -o obj/kiss_fft.o
        gcc -O3 -fPIC -I. -c kiss_fftr.c -o obj/kiss_fftr.o
        # Создаем библиотеку
        ar rcs libkissfft-float.a obj/kiss_fft.o obj/kiss_fftr.o
        # Устанавливаем
        cp libkissfft-float.a /mingw64/lib/
        cp kiss_fft.h /mingw64/include/
        cp kiss_fftr.h /mingw64/include/
        echo "kissfft installed successfully"

    # Кэширование liquid-dsp
    - name: Cache liquid-dsp
      id: cache-liquid-dsp
      uses: actions/cache@v4
      with:
        path: |
          /mingw64/lib/libliquid.a
          /mingw64/include/liquid/
        key: ${{ runner.os }}-liquid-dsp-20241219

    # Установка liquid-dsp вручную (исправленная версия)
    - name: Install liquid-dsp manually
      if: steps.cache-liquid-dsp.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        echo "Installing liquid-dsp manually..."
        git clone https://github.com/jgaeddert/liquid-dsp.git  
        cd liquid-dsp
        sed -i '/target_link_libraries.*c m/d' CMakeLists.txt
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/mingw64 -DBUILD_SHARED_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_AUTOTESTS=OFF -DBUILD_BENCHMARKS=OFF
        cmake --build . -j$(nproc)
        cmake --install .
        echo "liquid-dsp installed successfully"

    # Кэширование custom rtl-sdr
    - name: Cache custom rtl-sdr
      id: cache-rtl-sdr
      uses: actions/cache@v4
      with:
        path: |
          /mingw64/lib/librtlsdr.a
          /mingw64/lib/pkgconfig/librtlsdr.pc
          /mingw64/include/rtl-sdr.h
          /mingw64/include/rtl-sdr_export.h
        key: ${{ runner.os }}-rtl-sdr-fast_retune-20241219

    # Загрузка и установка custom rtl-sdr
    - name: Download and build custom rtl-sdr
      if: steps.cache-rtl-sdr.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        git clone https://gitea.osmocom.org/sultanqasim/rtl-sdr.git  
        cd rtl-sdr
        git checkout fast_retune
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/mingw64 -DBUILD_SHARED_LIBS=OFF
        make -j$(nproc)
        make install
        echo "rtl-sdr installed successfully"

    # Сборка freqmon
    - name: Compile freqmon
      shell: msys2 {0}
      run: |
        g++ -O3 -march=native -ffast-math -std=c++23 -o freqmon.exe freqmon.cpp \
          -lrtlsdr -lkissfft-float -lpthread -lliquid -fpermissive -lSDL2 -lSDL2_ttf \
          -I/mingw64/include -L/mingw64/lib

    # Загрузка артефактов
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: freqmon-${{ runner.os }}
        path: |
          freqmon.exe
