name: Build freqmon with custom rtl-sdr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    # Установка MinGW на Windows
    - name: Set up MinGW (Windows)
      if: runner.os == 'Windows'
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    # Установка MSYS2 для Windows
    - name: Setup MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libusb
        update: true

    # Клонирование и установка custom rtl-sdr (Linux/macOS)
    - name: Clone and build custom rtl-sdr (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        git clone --depth 1 -b fast_retune https://gitea.osmocom.org/sultanqasim/rtl-sdr.git
        cd rtl-sdr
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
        make -j$(nproc)
        sudo make install
      shell: bash

    # Клонирование и установка custom rtl-sdr (Windows)
    - name: Clone and build custom rtl-sdr (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        git clone --depth 1 -b fast_retune https://gitea.osmocom.org/sultanqasim/rtl-sdr.git
        cd rtl-sdr
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/mingw64
        mingw32-make -j$(nproc)
        mingw32-make install

    # Установка остальных зависимостей (Linux/macOS)
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev libkissfft-dev libliquid-dev libsdl2-dev libsdl2-ttf-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install libusb kissfft liquid-dsp sdl2 sdl2_ttf

    # Сборка freqmon (Linux/macOS)
    - name: Compile freqmon (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        g++ -O3 -march=native -ffast-math -std=c++23 -o freqmon freqmon.cpp \
          -lrtlsdr -lkissfft-float -lpthread -lliquid -fpermissive -lSDL2 -lSDL2_ttf \
          -I/usr/local/include -L/usr/local/lib \
          -Wl,-rpath,/usr/local/lib

    # Сборка freqmon (Windows)
    - name: Compile freqmon (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        g++ -O3 -march=native -ffast-math -std=c++23 -o freqmon.exe freqmon.cpp \
          -lrtlsdr -lkissfft-float -lpthread -lliquid -fpermissive -lSDL2 -lSDL2_ttf \
          -I/mingw64/include -L/mingw64/lib \
          -Wl,-rpath,/mingw64/lib

    # Загрузка артефактов
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: freqmon-${{ runner.os }}
        path: |
          freqmon*
